### ISSUE TITLE
Lab 1 never prompts to run config file

### ISSUE THREAD

**Issue by rhit-koenigjl** [rhit-netsos/netsec-public#6]
**Is your feature request related to a problem? Please describe.**
With being relatively new to docker, I'm having to go boy blind faith in the instructions while trying to figure the in's and out's of the program. While I was trying to start on lab one, I was getting non-verbose errors when attempting to exec bin/bash from the hosts. This was because I never ran the config file generation script.

**Describe the solution you'd like**
Add a sentence under the "Getting the config" section header that says to run the config script.

**Describe alternatives you've considered**
Add wording that says to reference the prelab if you are struggling with docker.

**Additional context**
Working on lab 1 prior to class session, little docker experience, decent amount of bash experience.

**Comment by nouredd2** [comment]
Fixed in latest commit, thanks JL!
