### ISSUE TITLE
Lab1 network topology image typo

### ISSUE THREAD

**Issue by rhit-koenigjl** [rhit-netsos/netsec-public#7]
**Describe the bug**
The markdown image reference for the network topology diagram in Lab1 is not rendering

**To Reproduce**
1. Go to Lab1 on the course website
2. Scroll to the "Network Topology" sub-header
3. See error

**Expected behavior**
An image to render showing the network topology

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by nouredd2** [comment]
Closed in latest commit, thanks JL!
